### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Sparkenstein** [fosslife/delta#1]
- [x] Test cron job
- [x] Refactor code for modular approach
- [x] Shift core logic for both post and get request to middlewares
- [x] Add authentication
- [x] Remove blocking code
- [ ] API testing if possible
- [ ] Add mailing/Notification service for events like Cron job started, stopped, cleanup done etc

**Comment by Sparkenstein** [comment]
Closing TODO as notification is not much of a feature right now, PRs are welcome :smiley:
